package com.sentrix.core.wrappers

/**
 * Represents analytics and reporting results generated by SentriX.
 */
data class AnalyticsResultWrapper(
    val reportId: String,
    val title: String,
    val summary: String,
    val generatedAt: Long = System.currentTimeMillis(),
    val periodStart: Long? = null,
    val periodEnd: Long? = null,
    val totalScans: Int = 0,
    val totalThreatsDetected: Int = 0,
    val resolvedThreats: Int = 0,
    val unresolvedThreats: Int = 0,
    val averageRiskScore: Double = 0.0,
    val deviceHealthScore: Int = 0,
    val recommendations: List<String> = emptyList(),
    val insights: List<String> = emptyList(),
    val metrics: Map<String, Any> = emptyMap()
) {

    /**
     * Returns true if any threats were detected.
     */
    fun hasThreats(): Boolean =
        totalThreatsDetected > 0

    /**
     * Returns true if there are unresolved threats.
     */
    fun hasUnresolvedThreats(): Boolean =
        unresolvedThreats > 0

    /**
     * Returns threat resolution percentage.
     */
    fun getResolutionRate(): Double {
        return if (totalThreatsDetected == 0) {
            100.0
        } else {
            (resolvedThreats.toDouble() / totalThreatsDetected) * 100
        }
    }

    /**
     * Returns a user-friendly risk level.
     */
    fun getRiskLevel(): String {
        return when {
            averageRiskScore <= 20 -> "Low"
            averageRiskScore <= 50 -> "Moderate"
            averageRiskScore <= 80 -> "High"
            else -> "Critical"
        }
    }

    /**
     * Returns a user-friendly device health status.
     */
    fun getHealthStatus(): String {
        return when (deviceHealthScore) {
            in 90..100 -> "Excellent"
            in 75..89 -> "Good"
            in 50..74 -> "Fair"
            in 25..49 -> "Poor"
            else -> "Critical"
        }
    }

    /**
     * Returns true if recommendations are available.
     */
    fun hasRecommendations(): Boolean =
        recommendations.isNotEmpty()

    /**
     * Returns true if insights are available.
     */
    fun hasInsights(): Boolean =
        insights.isNotEmpty()

    /**
     * Returns true if custom metrics are present.
     */
    fun hasMetrics(): Boolean =
        metrics.isNotEmpty()

    companion object {

        fun empty(): AnalyticsResultWrapper {
            return AnalyticsResultWrapper(
                reportId = "",
                title = "",
                summary = ""
            )
        }
    }
}
