package com.sentrix.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * SessionEntity
 *
 * Represents a user authentication session within SentriX.
 * A session is created when a user successfully logs in and
 * remains active until logout, expiration, or forced termination.
 *
 * This entity helps track active devices, monitor suspicious
 * login activity, and support session management features.
 */
@Entity(tableName = "sessions")
data class SessionEntity(

    /**
     * Local database primary key.
     * Automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Unique session identifier.
     * Typically generated using UUID.
     */
    val sessionId: String,

    /**
     * Associated user identifier.
     * Links the session to a specific user account.
     */
    val userId: String,

    /**
     * Device identifier from which the session originated.
     */
    val deviceId: String,

    /**
     * Device name or model.
     * Example: "Samsung Galaxy S24"
     */
    val deviceName: String,

    /**
     * Operating system information.
     * Example: "Android 15"
     */
    val osVersion: String,

    /**
     * IP address used during login.
     */
    val ipAddress: String,

    /**
     * Approximate login location.
     * Example: "Chennai, India"
     */
    val location: String? = null,

    /**
     * Authentication method used.
     * Examples:
     * PASSWORD
     * BIOMETRIC
     * OTP
     * GOOGLE_SIGN_IN
     */
    val authenticationMethod: String,

    /**
     * Indicates whether multi-factor authentication was used.
     */
    val mfaEnabled: Boolean,

    /**
     * Session start timestamp.
     */
    val loginTime: Date,

    /**
     * Last activity timestamp.
     * Updated whenever user performs actions.
     */
    val lastActivityTime: Date,

    /**
     * Session expiration timestamp.
     */
    val expiresAt: Date,

    /**
     * Logout timestamp.
     * Null if session is still active.
     */
    val logoutTime: Date? = null,

    /**
     * Indicates whether the session is currently active.
     */
    val isActive: Boolean = true,

    /**
     * Indicates whether suspicious activity was detected
     * during this session.
     */
    val isSuspicious: Boolean = false,

    /**
     * Risk score assigned by SentriX security engine.
     * Example range: 0–100.
     */
    val riskScore: Int = 0,

    /**
     * Optional reason for session termination.
     * Examples:
     * USER_LOGOUT
     * SESSION_EXPIRED
     * SECURITY_VIOLATION
     * FORCED_LOGOUT
     */
    val terminationReason: String? = null,

    /**
     * Timestamp when this record was created.
     */
    val createdAt: Date = Date(),

    /**
     * Timestamp when this record was last updated.
     */
    val updatedAt: Date = Date()
)
