package com.sentrix.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * NotificationEntity
 *
 * Represents notifications generated by SentriX.
 *
 * Notifications can be created for:
 * - Threat detections
 * - Security alerts
 * - Privacy warnings
 * - Device trust changes
 * - Scan completion events
 * - Authentication activities
 * - Security recommendations
 * - System updates
 *
 * This entity helps maintain a history of notifications
 * and allows users to review past security events.
 */
@Entity(tableName = "notifications")
data class NotificationEntity(

    /**
     * Local database primary key.
     * Automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Unique notification identifier.
     */
    val notificationId: String,

    /**
     * Notification title displayed to the user.
     *
     * Example:
     * "Threat Detected"
     * "Device Security Warning"
     */
    val title: String,

    /**
     * Detailed notification message.
     */
    val message: String,

    /**
     * Notification category.
     *
     * Examples:
     * THREAT
     * SECURITY
     * PRIVACY
     * SCAN
     * AUTHENTICATION
     * SYSTEM
     * RECOMMENDATION
     */
    val category: String,

    /**
     * Notification severity level.
     *
     * Examples:
     * INFO
     * LOW
     * MEDIUM
     * HIGH
     * CRITICAL
     */
    val severity: String,

    /**
     * Related entity identifier.
     *
     * Can reference:
     * - Threat ID
     * - Scan ID
     * - Session ID
     * - Security Report ID
     */
    val referenceId: String? = null,

    /**
     * Indicates whether the notification
     * has been viewed by the user.
     */
    val isRead: Boolean = false,

    /**
     * Indicates whether the notification
     * requires immediate user action.
     */
    val actionRequired: Boolean = false,

    /**
     * Optional action label.
     *
     * Examples:
     * "Scan Now"
     * "Review Threat"
     * "Update Settings"
     */
    val actionLabel: String? = null,

    /**
     * Deep-link destination or navigation route
     * within the application.
     */
    val actionRoute: String? = null,

    /**
     * Determines whether the notification
     * should be displayed as a push notification.
     */
    val isPushNotification: Boolean = true,

    /**
     * Indicates whether the notification
     * has already been delivered.
     */
    val isDelivered: Boolean = false,

    /**
     * Notification creation timestamp.
     */
    val createdAt: Date = Date(),

    /**
     * Timestamp when the notification
     * was delivered to the user.
     */
    val deliveredAt: Date? = null,

    /**
     * Timestamp when the user opened
     * or read the notification.
     */
    val readAt: Date? = null,

    /**
     * Record last update timestamp.
     */
    val updatedAt: Date = Date()
)
