package com.sentrix.data.remote.requests

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request DTO used to submit or generate a threat report in SentriX.
 *
 * This request can be used when:
 * - Reporting a detected threat to the backend
 * - Sending suspicious files/URLs for cloud analysis
 * - Generating a detailed security report
 * - Uploading threat intelligence data
 *
 * Example API Endpoint:
 * POST /api/v1/threats/report
 */
@Serializable
data class ThreatReportRequest(

    // Unique identifier of the user submitting the report
    @SerialName("user_id")
    val userId: String,

    // Unique identifier of the device where the threat was detected
    @SerialName("device_id")
    val deviceId: String,

    // Unique identifier of the detected threat
    @SerialName("threat_id")
    val threatId: String,

    // Name of the threat
    // Example: "Banking Trojan", "Phishing Website"
    @SerialName("threat_name")
    val threatName: String,

    // Type/category of threat
    // Example:
    // MALWARE, PHISHING, SPYWARE, RANSOMWARE, SCAM_SMS
    @SerialName("threat_type")
    val threatType: String,

    // Severity level assigned by SentriX
    // Possible values:
    // LOW, MEDIUM, HIGH, CRITICAL
    @SerialName("severity")
    val severity: String,

    // Detailed description of the threat
    @SerialName("description")
    val description: String,

    // Package name if the threat originated from an application
    @SerialName("package_name")
    val packageName: String? = null,

    // File path if the threat was detected in a file
    @SerialName("file_path")
    val filePath: String? = null,

    // URL associated with the threat
    // Example: phishing or scam website URL
    @SerialName("source_url")
    val sourceUrl: String? = null,

    // SHA-256 hash of the suspicious file (if available)
    @SerialName("file_hash")
    val fileHash: String? = null,

    // Risk score generated by the SentriX AI engine
    // Range: 0 - 100
    @SerialName("risk_score")
    val riskScore: Int = 0,

    // Action taken by the user or system
    // Example:
    // QUARANTINED, REMOVED, IGNORED, BLOCKED
    @SerialName("action_taken")
    val actionTaken: String = "DETECTED",

    // Timestamp when the threat was detected
    @SerialName("detected_at")
    val detectedAt: Long = System.currentTimeMillis(),

    // Indicates whether cloud analysis should be performed
    @SerialName("request_cloud_analysis")
    val requestCloudAnalysis: Boolean = true,

    // Indicates whether the report should be shared
    // with the SentriX threat intelligence network
    @SerialName("share_anonymously")
    val shareAnonymously: Boolean = true,

    // Additional contextual information
    //
    // Example:
    // "network_type" -> "WIFI"
    // "scan_type" -> "FULL"
    // "country" -> "India"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
