package com.sentrix.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * DTO representing the overall trust status of a device.
 *
 * SentriX uses this information to determine whether a device
 * can be considered secure, compromised, or suspicious.
 *
 * This data is typically obtained from:
 * - Device integrity checks
 * - Root/Jailbreak detection
 * - Boot verification
 * - Security policy validation
 * - Behavioral analysis
 */
@Serializable
data class DeviceTrustDto(

    // Unique identifier for this trust assessment
    @SerialName("trust_id")
    val trustId: String,

    // Unique identifier of the device
    @SerialName("device_id")
    val deviceId: String,

    // Overall trust score assigned by SentriX
    // Range: 0 - 100
    // Higher score = More trustworthy device
    @SerialName("trust_score")
    val trustScore: Int = 100,

    // Overall trust level
    // Example:
    // TRUSTED, WARNING, SUSPICIOUS, COMPROMISED
    @SerialName("trust_level")
    val trustLevel: String,

    // Indicates whether the device is considered trusted
    @SerialName("is_trusted")
    val isTrusted: Boolean = true,

    // Indicates whether the device is rooted
    @SerialName("is_rooted")
    val isRooted: Boolean = false,

    // Indicates whether a custom ROM is installed
    @SerialName("has_custom_rom")
    val hasCustomRom: Boolean = false,

    // Indicates whether USB debugging is enabled
    @SerialName("usb_debugging_enabled")
    val usbDebuggingEnabled: Boolean = false,

    // Indicates whether Developer Options are enabled
    @SerialName("developer_options_enabled")
    val developerOptionsEnabled: Boolean = false,

    // Indicates whether the bootloader is unlocked
    @SerialName("bootloader_unlocked")
    val bootloaderUnlocked: Boolean = false,

    // Indicates whether Google Play Protect is enabled
    @SerialName("play_protect_enabled")
    val playProtectEnabled: Boolean = true,

    // Indicates whether screen lock protection exists
    @SerialName("screen_lock_enabled")
    val screenLockEnabled: Boolean = true,

    // Indicates whether biometric authentication is configured
    @SerialName("biometric_enabled")
    val biometricEnabled: Boolean = false,

    // Indicates whether the device is encrypted
    @SerialName("device_encrypted")
    val deviceEncrypted: Boolean = true,

    // Indicates whether Secure Boot verification succeeded
    @SerialName("secure_boot_enabled")
    val secureBootEnabled: Boolean = true,

    // Indicates whether the device passed SafetyNet/Play Integrity checks
    @SerialName("integrity_passed")
    val integrityPassed: Boolean = true,

    // Number of security policy violations detected
    @SerialName("policy_violation_count")
    val policyViolationCount: Int = 0,

    // List of detected trust issues
    // Example:
    // "Root access detected"
    // "Bootloader unlocked"
    @SerialName("trust_issues")
    val trustIssues: List<String> = emptyList(),

    // Recommended actions generated by SentriX
    @SerialName("recommendations")
    val recommendations: List<String> = emptyList(),

    // Timestamp of the latest trust evaluation
    @SerialName("evaluated_at")
    val evaluatedAt: Long,

    // Version of the trust engine used
    @SerialName("engine_version")
    val engineVersion: String = "",

    // Additional backend or device information
    // Example:
    // "verified_boot_state" -> "GREEN"
    // "play_integrity_verdict" -> "MEETS_DEVICE_INTEGRITY"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
