package com.sentrix.data.repository.scanner

import com.sentrix.core.exceptions.NetworkException
import com.sentrix.core.exceptions.ServerException
import com.sentrix.core.exceptions.UnknownException
import com.sentrix.data.local.dao.ScanHistoryDao
import com.sentrix.data.local.entities.ScanHistoryEntity
import com.sentrix.data.remote.api.ScanApiService
import com.sentrix.data.remote.dto.ScanHistoryDto
import com.sentrix.domain.models.ScanResult
import com.sentrix.domain.repository.ScanHistoryRepository
import retrofit2.HttpException
import java.io.IOException
import javax.inject.Inject
import javax.inject.Singleton

/**
 * SentriX - Scan History Repository Implementation
 *
 * Package:
 * com.sentrix.data.repository.scanner
 *
 * Responsibility:
 * ------------------------------------------------------------
 * Central repository responsible for persisted scan history.
 *
 * Scan history may contain results generated by:
 *
 * - Quick Scan
 * - Smart Scan
 * - Deep Scan
 * - Targeted Scan
 * - APK Scan
 * - File Scan
 * - URL Scan
 * - Background Scan
 * - Scheduled Scan
 *
 * The repository manages:
 *
 * - Saving scan results.
 * - Retrieving scan history.
 * - Retrieving individual scans.
 * - Retrieving the latest scan.
 * - Filtering by scan type.
 * - Filtering by status.
 * - Filtering by threat presence.
 * - Filtering by risk score.
 * - Filtering by date range.
 * - Updating scan status.
 * - Deleting old scan history.
 * - Clearing scan history.
 * - Synchronizing history with backend.
 * - Mapping DTO <-> Domain <-> Entity.
 * - Translating infrastructure exceptions.
 *
 * IMPORTANT:
 * ------------------------------------------------------------
 * This repository does NOT perform scanning.
 *
 * It does not decide:
 *
 * - Whether an application is malicious.
 * - Whether a file is dangerous.
 * - Which scan should be performed.
 * - How risk scores are calculated.
 *
 * Those responsibilities belong to Domain/security engines.
 *
 * Clean Architecture:
 *
 * Domain
 *    │
 *    ▼
 * ScanHistoryRepository
 *    │
 *    ▼
 * ScanHistoryRepositoryImpl
 *    │
 *    ├──────────────► ScanHistoryDao
 *    │                     │
 *    │                     ▼
 *    │               ScanHistoryEntity
 *    │
 *    └──────────────► ScanApiService
 *                          │
 *                          ▼
 *                    ScanHistoryDto
 */
@Singleton
class ScanHistoryRepositoryImpl @Inject constructor(
    private val scanHistoryDao: ScanHistoryDao,
    private val scanApiService: ScanApiService
) : ScanHistoryRepository {

    /**
     * Retrieves all available scan history.
     *
     * Local database is used as the primary source because
     * scan history should remain available offline.
     */
    override suspend fun getAllScanHistory():
        Result<List<ScanResult>> {

        return try {

            val entities =
                scanHistoryDao.getAllScanHistory()

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves a single scan using its unique ID.
     */
    override suspend fun getScanById(
        scanId: String
    ): Result<ScanResult?> {

        return try {

            if (scanId.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan ID cannot be blank."
                    )
                )
            }

            val entity =
                scanHistoryDao.getScanById(scanId)

            Result.success(
                entity?.toDomain()
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves the most recently completed scan.
     */
    override suspend fun getLatestScan():
        Result<ScanResult?> {

        return try {

            val entity =
                scanHistoryDao.getLatestScan()

            Result.success(
                entity?.toDomain()
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves the most recent scans.
     */
    override suspend fun getRecentScans(
        limit: Int
    ): Result<List<ScanResult>> {

        return try {

            if (limit <= 0) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan history limit must be greater than zero."
                    )
                )
            }

            val entities =
                scanHistoryDao.getRecentScans(limit)

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scans belonging to a specific scan type.
     *
     * Examples:
     *
     * QUICK
     * SMART
     * DEEP
     * TARGETED
     * APK
     * FILE
     * URL
     * BACKGROUND
     */
    override suspend fun getScansByType(
        scanType: String
    ): Result<List<ScanResult>> {

        return try {

            if (scanType.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan type cannot be blank."
                    )
                )
            }

            val entities =
                scanHistoryDao.getScansByType(scanType)

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scans by execution status.
     *
     * Examples:
     *
     * QUEUED
     * RUNNING
     * COMPLETED
     * FAILED
     * CANCELLED
     */
    override suspend fun getScansByStatus(
        status: String
    ): Result<List<ScanResult>> {

        return try {

            if (status.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan status cannot be blank."
                    )
                )
            }

            val entities =
                scanHistoryDao.getScansByStatus(status)

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scans that detected at least one threat.
     */
    override suspend fun getScansWithThreats(
        limit: Int
    ): Result<List<ScanResult>> {

        return try {

            if (limit <= 0) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan limit must be greater than zero."
                    )
                )
            }

            val entities =
                scanHistoryDao.getScansWithThreats(limit)

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scans whose risk score is at or above the
     * supplied threshold.
     */
    override suspend fun getScansAboveRiskScore(
        minimumRiskScore: Double
    ): Result<List<ScanResult>> {

        return try {

            if (minimumRiskScore !in 0.0..100.0) {
                return Result.failure(
                    IllegalArgumentException(
                        "Risk score must be between 0 and 100."
                    )
                )
            }

            val entities =
                scanHistoryDao.getScansAboveRiskScore(
                    minimumRiskScore
                )

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scan history between two timestamps.
     */
    override suspend fun getScansBetween(
        startTime: Long,
        endTime: Long
    ): Result<List<ScanResult>> {

        return try {

            if (startTime > endTime) {
                return Result.failure(
                    IllegalArgumentException(
                        "Start time cannot be after end time."
                    )
                )
            }

            val entities =
                scanHistoryDao.getScansBetween(
                    startTime = startTime,
                    endTime = endTime
                )

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves scans performed after a specified timestamp.
     *
     * Useful for incremental history synchronization.
     */
    override suspend fun getScansSince(
        timestamp: Long
    ): Result<List<ScanResult>> {

        return try {

            val entities =
                scanHistoryDao.getScansSince(timestamp)

            Result.success(
                entities.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Saves one scan result.
     *
     * Used by scanner engines after completing a scan.
     */
    override suspend fun saveScan(
        scanResult: ScanResult
    ): Result<Unit> {

        return try {

            scanHistoryDao.insertOrUpdate(
                scanResult.toEntity()
            )

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Saves multiple scan results.
     *
     * Bulk insertion is useful during synchronization.
     */
    override suspend fun saveScans(
        scanResults: List<ScanResult>
    ): Result<Unit> {

        return try {

            if (scanResults.isEmpty()) {
                return Result.success(Unit)
            }

            scanHistoryDao.insertOrUpdateAll(
                scanResults.map {
                    it.toEntity()
                }
            )

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Updates the status of an existing scan.
     */
    override suspend fun updateScanStatus(
        scanId: String,
        status: String
    ): Result<Unit> {

        return try {

            if (scanId.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan ID cannot be blank."
                    )
                )
            }

            if (status.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan status cannot be blank."
                    )
                )
            }

            scanHistoryDao.updateScanStatus(
                scanId = scanId,
                status = status
            )

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Deletes one scan-history entry.
     *
     * This affects only the local history database.
     */
    override suspend fun deleteScan(
        scanId: String
    ): Result<Unit> {

        return try {

            if (scanId.isBlank()) {
                return Result.failure(
                    IllegalArgumentException(
                        "Scan ID cannot be blank."
                    )
                )
            }

            scanHistoryDao.deleteScanById(scanId)

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Deletes all scan history older than the supplied
     * timestamp.
     *
     * This supports configurable data-retention policies.
     */
    override suspend fun deleteOlderThan(
        timestamp: Long
    ): Result<Unit> {

        return try {

            scanHistoryDao.deleteScansOlderThan(
                timestamp
            )

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Clears the complete local scan history.
     */
    override suspend fun clearHistory():
        Result<Unit> {

        return try {

            scanHistoryDao.deleteAllScanHistory()

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Returns the number of locally stored scan records.
     */
    override suspend fun getScanCount():
        Result<Int> {

        return try {

            Result.success(
                scanHistoryDao.getScanCount()
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Returns the number of scans that detected threats.
     */
    override suspend fun getThreateningScanCount():
        Result<Int> {

        return try {

            Result.success(
                scanHistoryDao.getThreateningScanCount()
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Synchronizes scan history with the SentriX backend.
     *
     * Remote history is merged into the local database.
     */
    override suspend fun synchronizeHistory():
        Result<Unit> {

        return try {

            val response =
                scanApiService.getScanHistory()

            if (response.isNotEmpty()) {

                scanHistoryDao.insertOrUpdateAll(
                    response.map {
                        it.toEntity()
                    }
                )
            }

            Result.success(Unit)

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Retrieves remote scan history and stores it locally.
     *
     * Unlike synchronizeHistory(), this method also returns
     * the synchronized Domain models to the caller.
     */
    override suspend fun refreshHistory():
        Result<List<ScanResult>> {

        return try {

            val response =
                scanApiService.getScanHistory()

            if (response.isNotEmpty()) {

                scanHistoryDao.insertOrUpdateAll(
                    response.map {
                        it.toEntity()
                    }
                )
            }

            Result.success(
                response.map {
                    it.toDomain()
                }
            )

        } catch (exception: Exception) {

            Result.failure(
                mapScanHistoryException(exception)
            )
        }
    }

    /**
     * Converts remote ScanHistoryDto into Domain ScanResult.
     *
     * DTO -> Domain
     */
    private fun ScanHistoryDto.toDomain(): ScanResult {

        return ScanResult(
            scanId = scanId,
            scanType = scanType,
            status = status,
            startedAt = startedAt,
            completedAt = completedAt,
            scannedItems = scannedItems,
            threatsFound = threatsFound,
            criticalThreats = criticalThreats,
            highThreats = highThreats,
            mediumThreats = mediumThreats,
            lowThreats = lowThreats,
            riskScore = riskScore
        )
    }

    /**
     * Converts remote DTO into Room entity.
     *
     * DTO -> Entity
     */
    private fun ScanHistoryDto.toEntity():
        ScanHistoryEntity {

        return ScanHistoryEntity(
            scanId = scanId,
            scanType = scanType,
            status = status,
            startedAt = startedAt,
            completedAt = completedAt,
            scannedItems = scannedItems,
            threatsFound = threatsFound,
            criticalThreats = criticalThreats,
            highThreats = highThreats,
            mediumThreats = mediumThreats,
            lowThreats = lowThreats,
            riskScore = riskScore
        )
    }

    /**
     * Converts Domain ScanResult into Room entity.
     *
     * Domain -> Entity
     */
    private fun ScanResult.toEntity():
        ScanHistoryEntity {

        return ScanHistoryEntity(
            scanId = scanId,
            scanType = scanType,
            status = status,
            startedAt = startedAt,
            completedAt = completedAt,
            scannedItems = scannedItems,
            threatsFound = threatsFound,
            criticalThreats = criticalThreats,
            highThreats = highThreats,
            mediumThreats = mediumThreats,
            lowThreats = lowThreats,
            riskScore = riskScore
        )
    }

    /**
     * Converts Room entity into Domain ScanResult.
     *
     * Entity -> Domain
     */
    private fun ScanHistoryEntity.toDomain(): ScanResult {

        return ScanResult(
            scanId = scanId,
            scanType = scanType,
            status = status,
            startedAt = startedAt,
            completedAt = completedAt,
            scannedItems = scannedItems,
            threatsFound = threatsFound,
            criticalThreats = criticalThreats,
            highThreats = highThreats,
            mediumThreats = mediumThreats,
            lowThreats = lowThreats,
            riskScore = riskScore
        )
    }

    /**
     * Converts infrastructure exceptions into SentriX
     * application-level exceptions.
     */
    private fun mapScanHistoryException(
        exception: Exception
    ): Exception {

        return when (exception) {

            /**
             * Connectivity-related failures.
             */
            is IOException -> {
                NetworkException(
                    message = "Unable to communicate with the SentriX scan-history service.",
                    cause = exception
                )
            }

            /**
             * Backend HTTP failures.
             */
            is HttpException -> {

                when (exception.code()) {

                    400 -> {
                        ServerException(
                            "The scan-history request was invalid."
                        )
                    }

                    401 -> {
                        ServerException(
                            "The SentriX session is no longer authorized."
                        )
                    }

                    403 -> {
                        ServerException(
                            "You do not have permission to access scan history."
                        )
                    }

                    404 -> {
                        ServerException(
                            "The requested scan history was not found."
                        )
                    }

                    409 -> {
                        ServerException(
                            "Scan-history synchronization conflict occurred."
                        )
                    }

                    429 -> {
                        ServerException(
                            "Scan-history request limit exceeded."
                        )
                    }

                    in 500..599 -> {
                        ServerException(
                            "SentriX scan-history service is temporarily unavailable."
                        )
                    }

                    else -> {
                        ServerException(
                            "Scan-history request failed with HTTP ${exception.code()}."
                        )
                    }
                }
            }

            /**
             * Preserve already translated exceptions.
             */
            is NetworkException,
            is ServerException -> {
                exception
            }

            /**
             * Unexpected database/infrastructure failure.
             */
            else -> {
                UnknownException(
                    message = "An unexpected scan-history repository error occurred.",
                    cause = exception
                )
            }
        }
    }
}
