package com.sentrix.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * DeviceTrustEntity
 *
 * Stores trust and security-related information about the current device.
 * This entity helps SentriX determine whether the device can be considered
 * trusted, suspicious, or compromised based on various security checks.
 */
@Entity(tableName = "device_trust")
data class DeviceTrustEntity(

    /**
     * Unique local database identifier.
     * Auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * Unique identifier for the trust record.
     * Can be used for syncing with remote systems.
     */
    val trustId: String,

    /**
     * Device model name.
     * Example: "Samsung Galaxy S24"
     */
    val deviceModel: String,

    /**
     * Device manufacturer.
     * Example: "Samsung", "Google", "OnePlus"
     */
    val manufacturer: String,

    /**
     * Android OS version.
     * Example: "Android 15"
     */
    val osVersion: String,

    /**
     * Indicates whether the device is rooted.
     * Rooted devices generally have higher security risks.
     */
    val isRooted: Boolean,

    /**
     * Indicates whether a custom ROM is installed.
     * Custom ROMs may bypass standard security controls.
     */
    val hasCustomRom: Boolean,

    /**
     * Indicates whether Developer Options are enabled.
     */
    val developerOptionsEnabled: Boolean,

    /**
     * Indicates whether USB Debugging is enabled.
     * This can increase attack surface.
     */
    val usbDebuggingEnabled: Boolean,

    /**
     * Indicates whether a screen lock is configured.
     * Devices without screen locks are less secure.
     */
    val screenLockEnabled: Boolean,

    /**
     * Indicates whether biometric authentication is available.
     */
    val biometricEnabled: Boolean,

    /**
     * Indicates whether device encryption is enabled.
     */
    val encryptionEnabled: Boolean,

    /**
     * Indicates whether Play Protect is active.
     */
    val playProtectEnabled: Boolean,

    /**
     * Overall trust score calculated by SentriX.
     * Range example: 0 - 100.
     */
    val trustScore: Int,

    /**
     * Risk level assigned to the device.
     * Examples:
     * LOW, MEDIUM, HIGH, CRITICAL
     */
    val riskLevel: String,

    /**
     * Human-readable trust status.
     * Examples:
     * Trusted, Warning, Untrusted, Compromised
     */
    val trustStatus: String,

    /**
     * Reason or explanation for the trust evaluation.
     */
    val trustReason: String,

    /**
     * Timestamp of the most recent trust assessment.
     */
    val lastAssessmentDate: Date,

    /**
     * Record creation timestamp.
     */
    val createdAt: Date = Date(),

    /**
     * Record last update timestamp.
     */
    val updatedAt: Date = Date()
)
