package com.sentrix.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * DTO representing a complete security report received from the backend.
 *
 * This report is typically generated after a device scan or security audit
 * and provides an overall view of the device's security posture.
 */
@Serializable
data class SecurityReportDto(

    // Unique identifier for this report
    @SerialName("report_id")
    val reportId: String,

    // ID of the user/device associated with this report
    @SerialName("device_id")
    val deviceId: String,

    // Title displayed for the report
    // Example: "Weekly Security Assessment"
    @SerialName("report_title")
    val reportTitle: String,

    // Brief summary of the security report
    @SerialName("summary")
    val summary: String,

    // Overall security score assigned by SentriX
    // Range: 0 - 100
    @SerialName("security_score")
    val securityScore: Int = 100,

    // Overall risk score calculated by the threat engine
    // Higher score indicates greater risk
    @SerialName("risk_score")
    val riskScore: Int = 0,

    // Overall security status of the device
    // Example: SECURE, WARNING, CRITICAL
    @SerialName("security_status")
    val securityStatus: String,

    // Number of threats currently active on the device
    @SerialName("active_threat_count")
    val activeThreatCount: Int = 0,

    // Total number of threats detected during analysis
    @SerialName("total_threat_count")
    val totalThreatCount: Int = 0,

    // Number of installed apps analyzed
    @SerialName("apps_analyzed")
    val appsAnalyzed: Int = 0,

    // Number of files analyzed
    @SerialName("files_analyzed")
    val filesAnalyzed: Int = 0,

    // Number of suspicious network activities detected
    @SerialName("network_alert_count")
    val networkAlertCount: Int = 0,

    // Indicates whether the device is considered safe
    @SerialName("device_secure")
    val deviceSecure: Boolean = true,

    // List of recommendations generated by SentriX AI
    @SerialName("recommendations")
    val recommendations: List<String> = emptyList(),

    // List of warnings identified during analysis
    @SerialName("warnings")
    val warnings: List<String> = emptyList(),

    // Detailed list of threats included in this report
    @SerialName("threats")
    val threats: List<ThreatDto> = emptyList(),

    // Privacy audit findings associated with this report
    @SerialName("privacy_audits")
    val privacyAudits: List<PrivacyAuditDto> = emptyList(),

    // Time when the report was generated (Epoch milliseconds)
    @SerialName("generated_at")
    val generatedAt: Long,

    // Expiration time for this report if applicable
    @SerialName("expires_at")
    val expiresAt: Long? = null,

    // Version of the security engine that generated the report
    @SerialName("engine_version")
    val engineVersion: String = "",

    // Additional information returned by the backend
    // Example:
    // "vpn_status" -> "ACTIVE"
    // "firewall_status" -> "ENABLED"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
