package com.sentrix.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * SecurityReportEntity
 *
 * Represents a generated
 * security report within
 * the SentriX platform.
 *
 * Responsibilities:
 * - Store report metadata
 * - Track security posture
 * - Support compliance audits
 * - Enable report exports
 * - Maintain report history
 */
@Entity(
    tableName = "security_reports"
)
data class SecurityReportEntity(

    /**
     * Unique report identifier.
     */
    @PrimaryKey
    val reportId: String,

    /**
     * Report title.
     */
    val reportTitle: String,

    /**
     * Report type.
     *
     * DAILY
     * WEEKLY
     * MONTHLY
     * INCIDENT
     * COMPLIANCE
     * CUSTOM
     */
    val reportType: String,

    /**
     * Report description.
     */
    val description: String,

    /**
     * Overall security score.
     */
    val securityScore: Int,

    /**
     * Overall privacy score.
     */
    val privacyScore: Int,

    /**
     * Cyber defense score.
     */
    val cyberDefenseScore: Int,

    /**
     * Total threats detected.
     */
    val totalThreats: Int,

    /**
     * Critical threats detected.
     */
    val criticalThreats: Int,

    /**
     * High severity threats.
     */
    val highSeverityThreats: Int,

    /**
     * Medium severity threats.
     */
    val mediumSeverityThreats: Int,

    /**
     * Low severity threats.
     */
    val lowSeverityThreats: Int,

    /**
     * Resolved threats.
     */
    val resolvedThreats: Int,

    /**
     * Active threats.
     */
    val activeThreats: Int,

    /**
     * Total scans performed.
     */
    val totalScans: Int,

    /**
     * Successful scans.
     */
    val successfulScans: Int,

    /**
     * Failed scans.
     */
    val failedScans: Int,

    /**
     * Security recommendations count.
     */
    val recommendationsCount: Int,

    /**
     * Report summary.
     */
    val summary: String,

    /**
     * Export file path.
     */
    val reportPath: String?,

    /**
     * Export format.
     *
     * PDF
     * CSV
     * JSON
     * HTML
     */
    val exportFormat: String,

    /**
     * Generated by user/system.
     */
    val generatedBy: String,

    /**
     * Report generation timestamp.
     */
    val generatedAt: Long,

    /**
     * Report period start.
     */
    val reportStartDate: Long,

    /**
     * Report period end.
     */
    val reportEndDate: Long,

    /**
     * Last update timestamp.
     */
    val updatedAt: Long?
)
