package com.sentrix.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * DTO received from the remote API after a security scan.
 *
 * DTO = Data Transfer Object
 * This class represents the JSON response coming from the backend server.
 */
@Serializable
data class ScanResultDto(

    // Unique identifier for this scan
    @SerialName("scan_id")
    val scanId: String,

    // Type of scan performed
    // Example: QUICK, FULL, CUSTOM, REALTIME
    @SerialName("scan_type")
    val scanType: String,

    // Current status of the scan
    // Example: RUNNING, COMPLETED, FAILED
    @SerialName("scan_status")
    val scanStatus: String,

    // Timestamp when scan started (Epoch milliseconds)
    @SerialName("start_time")
    val startTime: Long,

    // Timestamp when scan finished
    // Nullable because an ongoing scan may not have an end time yet
    @SerialName("end_time")
    val endTime: Long? = null,

    // Total time taken by the scan in milliseconds
    @SerialName("duration_ms")
    val durationMs: Long = 0L,

    // Number of files scanned
    @SerialName("files_scanned")
    val filesScanned: Int = 0,

    // Number of installed applications scanned
    @SerialName("apps_scanned")
    val appsScanned: Int = 0,

    // Number of URLs or websites scanned
    @SerialName("urls_scanned")
    val urlsScanned: Int = 0,

    // Total number of threats found
    @SerialName("threats_detected")
    val threatsDetected: Int = 0,

    // Threat severity breakdown
    @SerialName("critical_threats")
    val criticalThreats: Int = 0,

    @SerialName("high_threats")
    val highThreats: Int = 0,

    @SerialName("medium_threats")
    val mediumThreats: Int = 0,

    @SerialName("low_threats")
    val lowThreats: Int = 0,

    // Overall risk score generated by SentriX AI Engine
    // Range example: 0 - 100
    @SerialName("risk_score")
    val riskScore: Int = 0,

    // Overall device security score
    // Higher score means safer device
    @SerialName("security_score")
    val securityScore: Int = 100,

    // Indicates whether the device is currently secure
    @SerialName("device_secure")
    val deviceSecure: Boolean = true,

    // Version of the scanning engine used
    @SerialName("scan_engine_version")
    val scanEngineVersion: String = "",

    // Detailed list of threats discovered during the scan
    @SerialName("threats")
    val threats: List<ThreatDto> = emptyList(),

    // Security recommendations generated by SentriX
    // Example:
    // "Remove suspicious app"
    // "Disable Accessibility Service"
    @SerialName("recommendations")
    val recommendations: List<String> = emptyList(),

    // Non-critical warnings generated during scan
    @SerialName("warnings")
    val warnings: List<String> = emptyList(),

    // Additional information returned by the server
    // Example:
    // "battery_usage" -> "LOW"
    // "network_status" -> "SECURE"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
