package com.sentrix.data.remote.responses

import com.sentrix.data.remote.dto.DeviceTrustDto
import com.sentrix.data.remote.dto.SecurityMetricsDto
import com.sentrix.data.remote.dto.ThreatDto
import com.sentrix.data.remote.dto.VPNStatusDto
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response DTO returned by the backend for the SentriX dashboard.
 *
 * This response provides a complete overview of the device's
 * current security posture and is typically shown on the Home screen.
 *
 * Used by:
 * - Dashboard Screen
 * - Home Screen
 * - Security Overview Widget
 * - Quick Insights Section
 *
 * Example API Endpoint:
 * GET /api/v1/dashboard/security
 */
@Serializable
data class SecurityDashboardResponse(

    // Indicates whether the dashboard request was successful
    @SerialName("success")
    val success: Boolean,

    // Human-readable message returned by the backend
    //
    // Examples:
    // "Dashboard data retrieved successfully"
    // "Unable to load dashboard"
    @SerialName("message")
    val message: String,

    // Overall device security score
    // Range: 0 - 100
    // Higher score = More secure device
    @SerialName("security_score")
    val securityScore: Int = 100,

    // Overall device risk score
    // Range: 0 - 100
    // Higher score = Higher risk
    @SerialName("risk_score")
    val riskScore: Int = 0,

    // Overall security state
    //
    // Examples:
    // SECURE
    // WARNING
    // AT_RISK
    // CRITICAL
    @SerialName("security_status")
    val securityStatus: String = "SECURE",

    // Number of active threats detected
    @SerialName("active_threat_count")
    val activeThreatCount: Int = 0,

    // Number of threats blocked today
    @SerialName("blocked_threats_today")
    val blockedThreatsToday: Int = 0,

    // Timestamp of the last completed scan
    @SerialName("last_scan_time")
    val lastScanTime: Long? = null,

    // Current security metrics collected by SentriX
    @SerialName("security_metrics")
    val securityMetrics: SecurityMetricsDto? = null,

    // Current VPN connection information
    @SerialName("vpn_status")
    val vpnStatus: VPNStatusDto? = null,

    // Device trust and integrity information
    @SerialName("device_trust")
    val deviceTrust: DeviceTrustDto? = null,

    // Recently detected threats
    // Usually limited to the latest few threats
    @SerialName("recent_threats")
    val recentThreats: List<ThreatDto> = emptyList(),

    // Recommended actions generated by SentriX AI
    //
    // Example:
    // "Run a full scan"
    // "Disable USB debugging"
    @SerialName("recommendations")
    val recommendations: List<String> = emptyList(),

    // Indicates whether immediate user attention is required
    @SerialName("action_required")
    val actionRequired: Boolean = false,

    // Premium subscription status
    @SerialName("premium_user")
    val premiumUser: Boolean = false,

    // Server timestamp when dashboard data was generated
    @SerialName("server_timestamp")
    val serverTimestamp: Long = System.currentTimeMillis(),

    // Additional dashboard information
    //
    // Example:
    // "engine_version" -> "v2.5.1"
    // "threat_feed_version" -> "2026.06.28"
    // "next_scheduled_scan" -> "1751035000000"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
