package com.sentrix.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * DTO representing a privacy audit result received from the backend.
 *
 * Privacy audits help SentriX analyze how installed applications
 * access sensitive data and identify potential privacy risks.
 */
@Serializable
data class PrivacyAuditDto(

    // Unique identifier for this privacy audit
    @SerialName("audit_id")
    val auditId: String,

    // Package name of the application being audited
    // Example: "com.whatsapp", "com.instagram.android"
    @SerialName("package_name")
    val packageName: String,

    // Human-readable application name
    @SerialName("app_name")
    val appName: String,

    // Version of the application installed on the device
    @SerialName("app_version")
    val appVersion: String = "",

    // Category of the application
    // Example: SOCIAL, FINANCE, PRODUCTIVITY, ENTERTAINMENT
    @SerialName("app_category")
    val appCategory: String = "",

    // Overall privacy risk score assigned by SentriX
    // Range: 0 - 100
    // Higher score = Greater privacy risk
    @SerialName("privacy_risk_score")
    val privacyRiskScore: Int = 0,

    // Overall privacy level of the application
    // Example: LOW, MEDIUM, HIGH, CRITICAL
    @SerialName("privacy_level")
    val privacyLevel: String,

    // Number of dangerous permissions requested by the app
    @SerialName("dangerous_permission_count")
    val dangerousPermissionCount: Int = 0,

    // Complete list of permissions used by the application
    @SerialName("permissions")
    val permissions: List<String> = emptyList(),

    // Sensitive resources accessed by the application
    // Example: Camera, Microphone, Contacts, Location
    @SerialName("sensitive_resources")
    val sensitiveResources: List<String> = emptyList(),

    // Permissions or behaviors considered suspicious
    @SerialName("suspicious_permissions")
    val suspiciousPermissions: List<String> = emptyList(),

    // Privacy issues detected during analysis
    @SerialName("privacy_issues")
    val privacyIssues: List<String> = emptyList(),

    // Recommendations generated by SentriX
    // Example:
    // "Revoke microphone access"
    // "Disable background location access"
    @SerialName("recommendations")
    val recommendations: List<String> = emptyList(),

    // Indicates whether the app can access the camera
    @SerialName("camera_access")
    val cameraAccess: Boolean = false,

    // Indicates whether the app can access the microphone
    @SerialName("microphone_access")
    val microphoneAccess: Boolean = false,

    // Indicates whether the app can access contacts
    @SerialName("contacts_access")
    val contactsAccess: Boolean = false,

    // Indicates whether the app can access device location
    @SerialName("location_access")
    val locationAccess: Boolean = false,

    // Indicates whether the app can read SMS messages
    @SerialName("sms_access")
    val smsAccess: Boolean = false,

    // Indicates whether the app can access storage/files
    @SerialName("storage_access")
    val storageAccess: Boolean = false,

    // Indicates whether the app is allowed to run in the background
    @SerialName("background_activity")
    val backgroundActivity: Boolean = false,

    // Indicates whether the app communicates with external servers
    @SerialName("network_access")
    val networkAccess: Boolean = false,

    // Whether the application is considered safe from a privacy perspective
    @SerialName("is_privacy_safe")
    val isPrivacySafe: Boolean = true,

    // Time when the audit was performed (Epoch milliseconds)
    @SerialName("audited_at")
    val auditedAt: Long,

    // Version of the privacy engine used for analysis
    @SerialName("engine_version")
    val engineVersion: String = "",

    // Additional information returned by the backend
    // Example:
    // "tracker_count" -> "12"
    // "ad_networks" -> "Google Ads, Meta Ads"
    @SerialName("metadata")
    val metadata: Map<String, String> = emptyMap()
)
