package com.sentrix.domain.models

/**
 * SecurityReport
 *
 * Represents a complete security assessment
 * generated by the SentriX platform.
 *
 * Used by:
 * - Security Dashboard
 * - Threat Analysis Engine
 * - AI Recommendation Engine
 * - Compliance Reporting
 * - Cloud Sync Services
 * - Security Auditing
 */
data class SecurityReport(

    /**
     * Unique report identifier.
     */
    val reportId: String,

    /**
     * Report generation timestamp.
     */
    val generatedAt: Long,

    /**
     * Device identifier.
     */
    val deviceId: String,

    /**
     * Overall security score.
     */
    val securityScore: Int,

    /**
     * Security status.
     */
    val status: SecurityStatus,

    /**
     * Total threats detected.
     */
    val totalThreats: Int,

    /**
     * Total malware detected.
     */
    val totalMalware: Int,

    /**
     * Critical threats count.
     */
    val criticalThreats: Int,

    /**
     * High severity threats count.
     */
    val highThreats: Int,

    /**
     * Medium severity threats count.
     */
    val mediumThreats: Int,

    /**
     * Low severity threats count.
     */
    val lowThreats: Int,

    /**
     * Detected threats.
     */
    val threats: List<Threat> = emptyList(),

    /**
     * Detected malware.
     */
    val malware: List<Malware> = emptyList(),

    /**
     * Security recommendations.
     */
    val recommendations: List<String> = emptyList(),

    /**
     * Scan duration in milliseconds.
     */
    val scanDuration: Long,

    /**
     * Report summary.
     */
    val summary: String,

    /**
     * Optional metadata.
     */
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Security status levels.
 */
enum class SecurityStatus {
    SECURE,
    LOW_RISK,
    MEDIUM_RISK,
    HIGH_RISK,
    CRITICAL_RISK
}
