package com.sentrix.domain.models

/**
 * SecurityRecommendation
 *
 * Represents an actionable security
 * recommendation generated by SentriX
 * security engines and AI analysis.
 *
 * Used by:
 * - AI Recommendation Engine
 * - Security Dashboard
 * - Threat Analysis Engine
 * - Risk Assessment Module
 * - Compliance Monitoring
 * - Incident Response System
 */
data class SecurityRecommendation(

    /**
     * Unique recommendation identifier.
     */
    val recommendationId: String,

    /**
     * Recommendation title.
     */
    val title: String,

    /**
     * Detailed description.
     */
    val description: String,

    /**
     * Recommendation category.
     */
    val category: RecommendationCategory,

    /**
     * Priority level.
     */
    val priority: RecommendationPriority,

    /**
     * Associated risk level.
     */
    val riskLevel: RiskLevel,

    /**
     * Estimated impact score.
     */
    val impactScore: Int,

    /**
     * Estimated implementation effort.
     */
    val effortLevel: EffortLevel,

    /**
     * Recommendation source.
     */
    val source: RecommendationSource,

    /**
     * Related threat identifier.
     */
    val relatedThreatId: String? = null,

    /**
     * Creation timestamp.
     */
    val createdAt: Long,

    /**
     * Whether recommendation
     * has been applied.
     */
    val isApplied: Boolean = false,

    /**
     * Additional metadata.
     */
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Recommendation categories.
 */
enum class RecommendationCategory {
    MALWARE_PROTECTION,
    DEVICE_SECURITY,
    NETWORK_SECURITY,
    APPLICATION_SECURITY,
    ACCOUNT_SECURITY,
    DATA_PRIVACY,
    COMPLIANCE,
    SYSTEM_UPDATE,
    THREAT_MITIGATION,
    GENERAL_SECURITY
}

/**
 * Recommendation priorities.
 */
enum class RecommendationPriority {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}

/**
 * Implementation effort levels.
 */
enum class EffortLevel {
    LOW,
    MEDIUM,
    HIGH
}

/**
 * Recommendation sources.
 */
enum class RecommendationSource {
    AI_ENGINE,
    THREAT_ANALYSIS,
    RISK_ENGINE,
    SECURITY_POLICY,
    COMPLIANCE_ENGINE,
    USER_BEHAVIOR_ANALYSIS,
    CLOUD_INTELLIGENCE,
    HYBRID
}
