package com.sentrix.domain.services

import com.sentrix.domain.models.Notification
import com.sentrix.domain.models.SecurityAlert
import com.sentrix.domain.models.ThreatIndicator
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Service responsible for notification management.
 *
 * This service creates, manages, filters,
 * and tracks notifications generated by SentriX.
 */
class NotificationService {

    /**
     * Creates notifications from security alerts.
     */
    suspend fun createNotifications(
        alerts: List<SecurityAlert>
    ): List<Notification> = withContext(Dispatchers.Default) {

        alerts.map { alert ->
            Notification(
                id = alert.id,
                title = alert.title,
                message = alert.message,
                priority = alert.severity,
                timestamp = alert.createdAt,
                isRead = false
            )
        }
    }

    /**
     * Creates notifications from threat indicators.
     */
    suspend fun createThreatNotifications(
        indicators: List<ThreatIndicator>
    ): List<Notification> = withContext(Dispatchers.Default) {

        indicators.map { threat ->
            Notification(
                id = threat.id,
                title = threat.threatName,
                message = threat.description,
                priority = threat.severity,
                timestamp = threat.timestamp,
                isRead = false
            )
        }
    }

    /**
     * Returns unread notifications.
     */
    suspend fun getUnreadNotifications(
        notifications: List<Notification>
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications.filter {
            !it.isRead
        }
    }

    /**
     * Returns read notifications.
     */
    suspend fun getReadNotifications(
        notifications: List<Notification>
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications.filter {
            it.isRead
        }
    }

    /**
     * Marks a notification as read.
     */
    suspend fun markAsRead(
        notification: Notification
    ): Notification = withContext(Dispatchers.Default) {

        notification.copy(
            isRead = true
        )
    }

    /**
     * Marks all notifications as read.
     */
    suspend fun markAllAsRead(
        notifications: List<Notification>
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications.map {
            it.copy(isRead = true)
        }
    }

    /**
     * Returns critical notifications.
     */
    suspend fun getCriticalNotifications(
        notifications: List<Notification>
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications.filter {
            it.priority.equals("CRITICAL", true)
        }
    }

    /**
     * Returns high-priority notifications.
     */
    suspend fun getHighPriorityNotifications(
        notifications: List<Notification>
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications.filter {
            it.priority.equals("HIGH", true)
        }
    }

    /**
     * Counts unread notifications.
     */
    suspend fun getUnreadCount(
        notifications: List<Notification>
    ): Int = withContext(Dispatchers.Default) {

        notifications.count {
            !it.isRead
        }
    }

    /**
     * Generates notification summary.
     */
    suspend fun generateNotificationSummary(
        notifications: List<Notification>
    ): String = withContext(Dispatchers.Default) {

        val unreadCount =
            notifications.count { !it.isRead }

        val criticalCount =
            notifications.count {
                it.priority.equals("CRITICAL", true)
            }

        val highCount =
            notifications.count {
                it.priority.equals("HIGH", true)
            }

        buildString {

            appendLine("SentriX Notification Summary")
            appendLine("============================")
            appendLine("Total Notifications: ${notifications.size}")
            appendLine("Unread Notifications: $unreadCount")
            appendLine("Critical Notifications: $criticalCount")
            appendLine("High Priority Notifications: $highCount")
        }
    }

    /**
     * Returns latest notifications.
     */
    suspend fun getLatestNotifications(
        notifications: List<Notification>,
        limit: Int = 10
    ): List<Notification> = withContext(Dispatchers.Default) {

        notifications
            .sortedByDescending { it.timestamp }
            .take(limit)
    }

    /**
     * Determines whether critical notifications exist.
     */
    suspend fun hasCriticalNotifications(
        notifications: List<Notification>
    ): Boolean = withContext(Dispatchers.Default) {

        notifications.any {
            it.priority.equals("CRITICAL", true)
        }
    }
}
