package com.sentrix.domain.models

/**
 * ScanStatistics
 *
 * Represents aggregated scanning statistics
 * generated by the SentriX security platform.
 *
 * This model provides analytical insights into
 * security scans, detection efficiency, scan
 * performance, threat trends, and remediation
 * effectiveness across devices, applications,
 * files, and network resources.
 *
 * Used by:
 * - ScanManager
 * - SecurityDashboard
 * - AnalyticsEngine
 * - ThreatAnalysisManager
 * - ReportingService
 * - ComplianceMonitoringSystem
 * - ExecutiveReportingModule
 * - AIThreatAnalyticsEngine
 */
data class ScanStatistics(

    /**
     * Unique statistics identifier.
     */
    val statisticsId: String,

    /**
     * Analysis period start timestamp.
     */
    val periodStart: Long,

    /**
     * Analysis period end timestamp.
     */
    val periodEnd: Long,

    /**
     * Total scans executed.
     */
    val totalScans: Int,

    /**
     * Successful scans completed.
     */
    val successfulScans: Int,

    /**
     * Failed scans.
     */
    val failedScans: Int,

    /**
     * Cancelled scans.
     */
    val cancelledScans: Int = 0,

    /**
     * Total threats detected.
     */
    val totalThreatsDetected: Int,

    /**
     * Total malware detections.
     */
    val totalMalwareDetected: Int,

    /**
     * Total phishing detections.
     */
    val totalPhishingDetected: Int,

    /**
     * Total suspicious activities detected.
     */
    val totalSuspiciousActivities: Int,

    /**
     * Total vulnerabilities identified.
     */
    val totalVulnerabilitiesDetected: Int,

    /**
     * Total threats blocked.
     */
    val totalThreatsBlocked: Int,

    /**
     * Total threats quarantined.
     */
    val totalThreatsQuarantined: Int,

    /**
     * Total incidents resolved.
     */
    val totalIncidentsResolved: Int,

    /**
     * Average scan duration in milliseconds.
     */
    val averageScanDuration: Long,

    /**
     * Fastest scan duration recorded.
     */
    val fastestScanDuration: Long,

    /**
     * Slowest scan duration recorded.
     */
    val slowestScanDuration: Long,

    /**
     * Overall detection rate percentage.
     */
    val detectionRate: Double,

    /**
     * Threat blocking effectiveness percentage.
     */
    val threatBlockingRate: Double,

    /**
     * Overall scan health status.
     */
    val scanHealthStatus: ScanHealthStatus,

    /**
     * Most frequently detected threats.
     */
    val topThreats: List<ThreatStatistic> =
        emptyList(),

    /**
     * Scan statistics grouped by scan type.
     */
    val scanTypeStatistics: List<ScanTypeStatistic> =
        emptyList(),

    /**
     * Security trend during the period.
     */
    val securityTrend: SecurityTrend =
        SecurityTrend.STABLE,

    /**
     * Additional metadata.
     */
    val metadata: Map<String, String> =
        emptyMap()
)

/**
 * Scan health indicators.
 *
 * Represents the overall operational
 * health of the scanning infrastructure.
 */
enum class ScanHealthStatus {

    /**
     * Scan operations functioning normally.
     */
    HEALTHY,

    /**
     * Minor performance degradation.
     */
    DEGRADED,

    /**
     * Significant scan issues detected.
     */
    UNSTABLE,

    /**
     * Critical scanning failures present.
     */
    CRITICAL
}

/**
 * ThreatStatistic
 *
 * Represents statistical information
 * about a specific threat category.
 */
data class ThreatStatistic(

    /**
     * Threat category.
     */
    val threatCategory: ThreatCategory,

    /**
     * Detection count.
     */
    val detectionCount: Int,

    /**
     * Percentage of total detections.
     */
    val percentage: Double,

    /**
     * Average severity score.
     */
    val averageSeverityScore: Double
)

/**
 * ScanTypeStatistic
 *
 * Represents statistics associated
 * with a specific scan type.
 */
data class ScanTypeStatistic(

    /**
     * Scan type.
     */
    val scanType: ScanType,

    /**
     * Total scans executed.
     */
    val totalScans: Int,

    /**
     * Successful scans.
     */
    val successfulScans: Int,

    /**
     * Failed scans.
     */
    val failedScans: Int,

    /**
     * Threats detected by this scan type.
     */
    val threatsDetected: Int,

    /**
     * Average scan duration.
     */
    val averageDuration: Long
)

/**
 * Scan type classifications.
 */
enum class ScanType {

    /**
     * Complete device scan.
     */
    FULL_SCAN,

    /**
     * Quick security scan.
     */
    QUICK_SCAN,

    /**
     * Custom targeted scan.
     */
    CUSTOM_SCAN,

    /**
     * Application security scan.
     */
    APPLICATION_SCAN,

    /**
     * Malware-focused scan.
     */
    MALWARE_SCAN,

    /**
     * Network security scan.
     */
    NETWORK_SCAN,

    /**
     * Vulnerability assessment scan.
     */
    VULNERABILITY_SCAN,

    /**
     * Cloud security scan.
     */
    CLOUD_SCAN
}
