package com.sentrix.domain.models

/**
 * SecurityMetrics
 *
 * Represents aggregated security metrics
 * and analytics generated by the SentriX
 * platform for monitoring security posture.
 *
 * Used by:
 * - SecurityDashboard
 * - AnalyticsEngine
 * - ThreatAnalysisManager
 * - ExecutiveReporting
 * - ComplianceMonitoring
 * - CloudAnalyticsPlatform
 */
data class SecurityMetrics(

    /**
     * Unique metrics identifier.
     */
    val metricsId: String,

    /**
     * Time period start.
     */
    val periodStart: Long,

    /**
     * Time period end.
     */
    val periodEnd: Long,

    /**
     * Overall security score.
     */
    val securityScore: Int,

    /**
     * Total scans executed.
     */
    val totalScans: Int,

    /**
     * Total threats detected.
     */
    val totalThreats: Int,

    /**
     * Total malware detected.
     */
    val totalMalware: Int,

    /**
     * Total security alerts generated.
     */
    val totalAlerts: Int,

    /**
     * Total intrusion attempts detected.
     */
    val totalIntrusions: Int,

    /**
     * Total blocked threats.
     */
    val blockedThreats: Int,

    /**
     * Total resolved incidents.
     */
    val resolvedIncidents: Int,

    /**
     * Average risk score.
     */
    val averageRiskScore: Double,

    /**
     * Average scan duration.
     */
    val averageScanDuration: Long,

    /**
     * Security trend.
     */
    val trend: SecurityTrend,

    /**
     * Top threat categories.
     */
    val topThreatCategories: List<ThreatCategoryMetric> = emptyList(),

    /**
     * Additional metadata.
     */
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Security trend indicators.
 */
enum class SecurityTrend {
    IMPROVING,
    STABLE,
    DECLINING,
    CRITICAL
}

/**
 * Threat category metric.
 */
data class ThreatCategoryMetric(

    /**
     * Threat category.
     */
    val category: ThreatCategory,

    /**
     * Number of detections.
     */
    val count: Int,

    /**
     * Percentage of total threats.
     */
    val percentage: Double
)
