package com.sentrix.domain.usecases

import com.sentrix.domain.models.SecurityMetrics
import com.sentrix.domain.models.ThreatLevel
import com.sentrix.domain.repositories.ThreatPredictionRepository

/**
 * PredictThreatUseCase
 *
 * Responsible for predicting potential future
 * cybersecurity threats using historical security
 * data, threat intelligence, behavioral patterns,
 * risk indicators, and analytics generated by
 * the SentriX platform.
 *
 * This use case enables proactive defense by
 * identifying emerging risks before they become
 * active security incidents.
 *
 * Used by:
 * - AIThreatPredictionEngine
 * - ThreatAnalysisManager
 * - SecurityDashboard
 * - CyberDefenseManager
 * - RiskAssessmentEngine
 * - SecurityAnalyticsPlatform
 * - ExecutiveReportingService
 * - RealtimeProtectionEngine
 *
 * Responsibilities:
 * - Predict future threats
 * - Analyze threat trends
 * - Evaluate attack likelihood
 * - Calculate prediction confidence
 * - Estimate future risk exposure
 * - Generate proactive recommendations
 */
class PredictThreatUseCase(
    private val repository: ThreatPredictionRepository
) {

    /**
     * Executes threat prediction analysis.
     *
     * @return ThreatPredictionResult
     */
    suspend operator fun invoke():
        ThreatPredictionResult {

        val securityMetrics =
            repository.getHistoricalMetrics()

        val threatIndicators =
            repository.getThreatIndicators()

        val predictedThreatLevel =
            predictThreatLevel(
                securityMetrics
            )

        val confidenceScore =
            calculateConfidence(
                securityMetrics.size
            )

        val estimatedRiskScore =
            calculateRiskScore(
                predictedThreatLevel
            )

        return ThreatPredictionResult(
            predictedAt =
                System.currentTimeMillis(),
            predictionWindowDays = 30,
            predictedThreatLevel =
                predictedThreatLevel,
            confidenceScore =
                confidenceScore,
            estimatedRiskScore =
                estimatedRiskScore,
            analyzedMetrics =
                securityMetrics.size,
            detectedIndicators =
                threatIndicators,
            recommendations =
                generateRecommendations(
                    predictedThreatLevel
                )
        )
    }

    /**
     * Predicts future threat level
     * using historical trends.
     */
    private fun predictThreatLevel(
        metrics: List<SecurityMetrics>
    ): ThreatLevel {

        if (metrics.isEmpty()) {
            return ThreatLevel.LOW
        }

        val averageRisk =
            metrics.map {
                it.averageRiskScore
            }.average()

        return when {

            averageRisk >= 80 ->
                ThreatLevel.CRITICAL

            averageRisk >= 60 ->
                ThreatLevel.HIGH

            averageRisk >= 30 ->
                ThreatLevel.MEDIUM

            else ->
                ThreatLevel.LOW
        }
    }

    /**
     * Calculates prediction confidence.
     *
     * Range:
     * 0 - 100
     */
    private fun calculateConfidence(
        metricCount: Int
    ): Int {

        return (metricCount * 10)
            .coerceIn(0, 100)
    }

    /**
     * Calculates estimated future risk.
     */
    private fun calculateRiskScore(
        threatLevel: ThreatLevel
    ): Int {

        return when (threatLevel) {

            ThreatLevel.LOW -> 20

            ThreatLevel.MEDIUM -> 50

            ThreatLevel.HIGH -> 75

            ThreatLevel.CRITICAL -> 95
        }
    }

    /**
     * Generates proactive security
     * recommendations.
     */
    private fun generateRecommendations(
        threatLevel: ThreatLevel
    ): List<String> {

        return when (threatLevel) {

            ThreatLevel.CRITICAL -> listOf(
                "Enable maximum protection mode",
                "Increase security monitoring",
                "Review incident response plans",
                "Perform organization-wide assessment"
            )

            ThreatLevel.HIGH -> listOf(
                "Strengthen security controls",
                "Increase threat monitoring",
                "Review high-risk assets"
            )

            ThreatLevel.MEDIUM -> listOf(
                "Monitor emerging threats",
                "Review security posture"
            )

            ThreatLevel.LOW -> listOf(
                "Maintain current protections"
            )
        }
    }
}

/**
 * ThreatPredictionResult
 *
 * Represents the outcome of
 * predictive threat analysis.
 */
data class ThreatPredictionResult(

    /**
     * Prediction timestamp.
     */
    val predictedAt: Long,

    /**
     * Prediction window in days.
     */
    val predictionWindowDays: Int,

    /**
     * Predicted threat level.
     */
    val predictedThreatLevel: ThreatLevel,

    /**
     * Prediction confidence score.
     *
     * Range:
     * 0 - 100
     */
    val confidenceScore: Int,

    /**
     * Estimated future risk score.
     */
    val estimatedRiskScore: Int,

    /**
     * Number of metrics analyzed.
     */
    val analyzedMetrics: Int,

    /**
     * Indicators used for prediction.
     */
    val detectedIndicators:
        List<ThreatPredictionIndicator>,

    /**
     * Proactive security recommendations.
     */
    val recommendations: List<String>
)

/**
 * ThreatPredictionIndicator
 *
 * Represents an indicator used
 * during predictive threat analysis.
 */
data class ThreatPredictionIndicator(

    /**
     * Indicator identifier.
     */
    val indicatorId: String,

    /**
     * Indicator name.
     */
    val name: String,

    /**
     * Indicator category.
     */
    val category:
        PredictionIndicatorCategory,

    /**
     * Indicator weight.
     */
    val weight: Double,

    /**
     * Indicator confidence.
     */
    val confidence: Double,

    /**
     * Indicator description.
     */
    val description: String
)

/**
 * Prediction indicator categories.
 */
enum class PredictionIndicatorCategory {

    /**
     * Historical threat activity.
     */
    THREAT_HISTORY,

    /**
     * Vulnerability trends.
     */
    VULNERABILITY,

    /**
     * User behavior analytics.
     */
    USER_BEHAVIOR,

    /**
     * Network activity.
     */
    NETWORK_ACTIVITY,

    /**
     * Endpoint security data.
     */
    ENDPOINT_SECURITY,

    /**
     * Threat intelligence feeds.
     */
    THREAT_INTELLIGENCE,

    /**
     * Security incident trends.
     */
    INCIDENT_ANALYTICS,

    /**
     * AI-generated indicators.
     */
    AI_ANALYSIS
}
