package com.sentrix.security.sslpinning

import android.content.Context
import android.os.Build
import java.net.InetAddress
import java.net.Socket
import java.security.GeneralSecurityException
import java.security.SecureRandom
import javax.net.ssl.SSLContext
import javax.net.ssl.SSLSocket
import javax.net.ssl.SSLSocketFactory

/**
 * SecureSSLSocketFactory
 *
 * Provides a hardened, platform-backed SSLSocketFactory for
 * SentriX network communication.
 *
 * Responsibilities:
 *
 * - Build SSLContext using the Android platform TrustManager.
 * - Create SSLSockets using the platform TLS implementation.
 * - Restrict enabled protocols to approved TLS versions.
 * - Optionally restrict enabled cipher suites.
 * - Ensure sockets are configured before use.
 * - Provide runtime security information.
 *
 * IMPORTANT:
 *
 * This class does NOT implement certificate pinning directly.
 *
 * Certificate/public-key pinning should remain in:
 *
 *     OkHttp CertificatePinner
 *
 * and the SentriX pinning validation components.
 *
 * This class also does NOT:
 *
 * - trust all certificates.
 * - disable certificate validation.
 * - install a permissive TrustManager.
 * - disable hostname verification.
 *
 * Security architecture:
 *
 * SecureSSLSocketFactory
 *          ↓
 * SSLContext
 *          ↓
 * Platform X509TrustManager
 *          ↓
 * Normal TLS certificate validation
 *          ↓
 * OkHttp CertificatePinner
 *          ↓
 * SentriX public-key pinning
 */
class SecureSSLSocketFactory(
    private val context: Context,
    private val trustManagerFactoryProvider:
        TrustManagerFactoryProvider,
    private val configuration:
        SecureSSLSocketFactoryConfiguration =
        SecureSSLSocketFactoryConfiguration()
) : SSLSocketFactory() {

    /**
     * Platform SSL context.
     */
    private val sslContext: SSLContext =
        createSSLContext()

    /**
     * Delegate factory generated by the platform SSL context.
     */
    private val delegateFactory:
        SSLSocketFactory =
        sslContext.socketFactory

    /**
     * Supported cipher suites exposed by the platform factory.
     */
    private val supportedCipherSuitesInternal:
        Array<String> =
        delegateFactory.supportedCipherSuites
            .clone()

    /**
     * Supported protocols exposed by the platform factory.
     */
    private val supportedProtocolsInternal:
        Array<String> =
        delegateFactory.supportedProtocols
            .clone()

    /**
     * Creates an SSLContext using the platform X509TrustManager.
     */
    private fun createSSLContext():
            SSLContext {

        val trustManager =
            trustManagerFactoryProvider
                .getX509TrustManager()

        val context =
            SSLContext.getInstance(
                configuration.sslProtocol
            )

        /**
         * Only the platform trust manager is supplied.
         *
         * No permissive TrustManager is installed.
         */
        context.init(
            null,
            arrayOf(
                trustManager
            ),
            SecureRandom()
        )

        return context
    }

    // ---------------------------------------------------------------------
    // Socket creation
    // ---------------------------------------------------------------------

    /**
     * Creates an unconnected SSL socket.
     */
    override fun createSocket():
            Socket {

        return configureSocket(
            delegateFactory.createSocket()
        )
    }

    /**
     * Creates an SSL socket connected to the specified host and port.
     */
    override fun createSocket(
        host: String,
        port: Int
    ): Socket {

        return configureSocket(
            delegateFactory.createSocket(
                host,
                port
            )
        )
    }

    /**
     * Creates an SSL socket connected to the specified InetAddress.
     */
    override fun createSocket(
        host: InetAddress,
        port: Int
    ): Socket {

        return configureSocket(
            delegateFactory.createSocket(
                host,
                port
            )
        )
    }

    /**
     * Creates an SSL socket using an existing local address.
     */
    override fun createSocket(
        host: String,
        port: Int,
        localHost: InetAddress,
        localPort: Int
    ): Socket {

        return configureSocket(
            delegateFactory.createSocket(
                host,
                port,
                localHost,
                localPort
            )
        )
    }

    /**
     * Creates an SSL socket using an existing local address.
     */
    override fun createSocket(
        address: InetAddress,
        port: Int,
        localAddress: InetAddress,
        localPort: Int
    ): Socket {

        return configureSocket(
            delegateFactory.createSocket(
                address,
                port,
                localAddress,
                localPort
            )
        )
    }

    /**
     * Wraps an existing connected socket with TLS.
     */
    override fun createSocket(
        socket: Socket,
        host: String,
        port: Int,
        autoClose: Boolean
    ): Socket {

        return configureSocket(
            delegateFactory.createSocket(
                socket,
                host,
                port,
                autoClose
            )
        )
    }

    // ---------------------------------------------------------------------
    // Cipher suites
    // ---------------------------------------------------------------------

    /**
     * Returns the cipher suites supported by the underlying
     * platform TLS implementation.
     */
    override fun getSupportedCipherSuites():
            Array<String> {

        return supportedCipherSuitesInternal
            .clone()
    }

    /**
     * Returns the cipher suites enabled by SentriX configuration.
     */
    override fun getDefaultCipherSuites():
            Array<String> {

        return resolveEnabledCipherSuites()
    }

    // ---------------------------------------------------------------------
    // Socket configuration
    // ---------------------------------------------------------------------

    /**
     * Configures an SSL socket before it is used.
     *
     * The method:
     *
     * 1. Restricts TLS protocols.
     * 2. Restricts cipher suites if configured.
     * 3. Enables hostname-related TLS features supported by the
     *    underlying Android implementation.
     */
    private fun configureSocket(
        socket: Socket
    ): Socket {

        if (
            socket !is SSLSocket
        ) {

            throw SecureSSLSocketFactoryException(
                "Underlying platform factory returned a non-SSLSocket."
            )
        }

        configureProtocols(
            socket
        )

        configureCipherSuites(
            socket
        )

        configureTlsExtensions(
            socket
        )

        return socket
    }

    /**
     * Enables only approved TLS protocol versions.
     *
     * Default configuration:
     *
     * TLS 1.3
     * TLS 1.2
     *
     * Older protocols are intentionally excluded.
     */
    private fun configureProtocols(
        socket: SSLSocket
    ) {

        val supported =
            socket.supportedProtocols
            .toSet()

        val requested =
            configuration
                .enabledProtocols

        val enabled =
            requested
                .filter {
                    supported.contains(it)
                }
                .toTypedArray()

        if (
            enabled.isEmpty()
        ) {

            throw SecureSSLSocketFactoryException(
                "None of the configured TLS protocols are supported by the device."
            )
        }

        socket.enabledProtocols =
            enabled
    }

    /**
     * Configures approved cipher suites.
     *
     * If no explicit cipher list is supplied, the platform's
     * default cipher configuration is retained.
     */
    private fun configureCipherSuites(
        socket: SSLSocket
    ) {

        val configured =
            configuration
                .enabledCipherSuites

        if (
            configured.isEmpty()
        ) {

            return
        }

        val supported =
            socket.supportedCipherSuites
                .toSet()

        val enabled =
            configured
                .filter {
                    supported.contains(it)
                }
                .toTypedArray()

        if (
            enabled.isEmpty()
        ) {

            throw SecureSSLSocketFactoryException(
                "None of the configured TLS cipher suites are supported by the device."
            )
        }

        socket.enabledCipherSuites =
            enabled
    }

    /**
     * Configures supported TLS extensions.
     *
     * Android manages many TLS extensions internally. We deliberately
     * avoid manually manipulating low-level extensions here.
     *
     * SNI is normally handled by the platform/OkHttp based on the
     * destination hostname.
     */
    private fun configureTlsExtensions(
        socket: SSLSocket
    ) {

        /**
         * Android's platform TLS stack handles SNI and other TLS
         * extensions through the normal SSLSocket/SSLParameters
         * implementation.
         *
         * No custom extension manipulation is required here.
         */
    }

    /**
     * Resolves configured cipher suites.
     *
     * Invalid/unsupported cipher names are removed.
     */
    private fun resolveEnabledCipherSuites():
            Array<String> {

        val configured =
            configuration
                .enabledCipherSuites

        if (
            configured.isEmpty()
        ) {

            return delegateFactory
                .defaultCipherSuites
                .clone()
        }

        val supported =
            supportedCipherSuitesInternal
                .toSet()

        val result =
            configured
                .filter {
                    supported.contains(it)
                }

        if (
            result.isEmpty()
        ) {

            throw SecureSSLSocketFactoryException(
                "Configured cipher suites are not supported."
            )
        }

        return result.toTypedArray()
    }

    /**
     * Returns the platform supported protocols.
     */
    fun getSupportedTlsProtocols():
            List<String> {

        return supportedProtocolsInternal
            .toList()
    }

    /**
     * Returns the protocols configured for SentriX.
     */
    fun getConfiguredTlsProtocols():
            List<String> {

        return configuration
            .enabledProtocols
    }

    /**
     * Returns the currently configured cipher suites.
     */
    fun getConfiguredCipherSuites():
            List<String> {

        return configuration
            .enabledCipherSuites
            .toList()
    }

    /**
     * Returns the Android API level.
     */
    fun getAndroidApiLevel(): Int {

        return Build.VERSION.SDK_INT
    }

    /**
     * Returns the application package name.
     */
    fun getPackageName(): String {

        return context.packageName
    }

    /**
     * Returns the underlying SSLContext protocol.
     */
    fun getSslProtocol(): String {

        return configuration.sslProtocol
    }

    /**
     * Returns the provider used by the SSLContext.
     */
    fun getSslProviderName(): String {

        return sslContext.provider.name
    }

    /**
     * Returns whether TLS 1.3 is available.
     */
    fun supportsTls13(): Boolean {

        return supportedProtocolsInternal
            .contains(
                TLS_1_3
            )
    }

    /**
     * Returns whether TLS 1.2 is available.
     */
    fun supportsTls12(): Boolean {

        return supportedProtocolsInternal
            .contains(
                TLS_1_2
            )
    }

    /**
     * Performs a security configuration validation.
     */
    fun validate():
            SecureSSLSocketFactoryValidationResult {

        val findings =
            mutableListOf<SecureSSLSocketFinding>()

        var checksPerformed = 0
        var checksPassed = 0
        var checksFailed = 0

        /**
         * ---------------------------------------------------------
         * SSLContext validation
         * ---------------------------------------------------------
         */
        checksPerformed++

        try {

            sslContext.protocol

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.SSL_CONTEXT_AVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "SSLContext available",
                description =
                    "SentriX successfully initialized the platform SSLContext.",
                value =
                    sslContext.protocol,
                valid = true
            )

        } catch (exception: Exception) {

            checksFailed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.SSL_CONTEXT_UNAVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.CRITICAL,
                title =
                    "SSLContext unavailable",
                description =
                    "SentriX could not access the configured SSLContext.",
                value =
                    exception.javaClass.simpleName,
                valid = false
            )
        }

        /**
         * ---------------------------------------------------------
         * Trust manager validation
         * ---------------------------------------------------------
         */
        checksPerformed++

        try {

            trustManagerFactoryProvider
                .getX509TrustManager()

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TRUST_MANAGER_AVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "Platform trust manager available",
                description =
                    "The SSL socket factory uses a platform X509TrustManager.",
                valid = true
            )

        } catch (exception: Exception) {

            checksFailed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TRUST_MANAGER_UNAVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.CRITICAL,
                title =
                    "Platform trust manager unavailable",
                description =
                    "The SSL socket factory cannot obtain a valid platform trust manager.",
                value =
                    exception.javaClass.simpleName,
                valid = false
            )
        }

        /**
         * ---------------------------------------------------------
         * TLS 1.3
         * ---------------------------------------------------------
         */
        checksPerformed++

        if (
            supportsTls13()
        ) {

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TLS_1_3_SUPPORTED,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "TLS 1.3 supported",
                description =
                    "The underlying Android TLS implementation supports TLS 1.3.",
                valid = true
            )

        } else {

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TLS_1_3_UNAVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.LOW,
                title =
                    "TLS 1.3 unavailable",
                description =
                    "TLS 1.3 is not available on this device.",
                value =
                    Build.VERSION.SDK_INT.toString(),
                valid = false
            )
        }

        /**
         * ---------------------------------------------------------
         * TLS 1.2
         * ---------------------------------------------------------
         */
        checksPerformed++

        if (
            supportsTls12()
        ) {

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TLS_1_2_SUPPORTED,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "TLS 1.2 supported",
                description =
                    "The underlying Android TLS implementation supports TLS 1.2.",
                valid = true
            )

        } else {

            checksFailed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.TLS_1_2_UNAVAILABLE,
                severity =
                    SecureSSLSocketFindingSeverity.HIGH,
                title =
                    "TLS 1.2 unavailable",
                description =
                    "TLS 1.2 is not available on the device.",
                valid = false
            )
        }

        /**
         * ---------------------------------------------------------
         * Configured protocol availability
         * ---------------------------------------------------------
         */
        checksPerformed++

        val configuredProtocols =
            configuration
                .enabledProtocols

        val unsupportedProtocols =
            configuredProtocols
                .filterNot {
                    supportedProtocolsInternal
                        .contains(it)
                }

        if (
            unsupportedProtocols.isEmpty()
        ) {

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.PROTOCOL_CONFIGURATION_VALID,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "TLS protocol configuration valid",
                description =
                    "All configured TLS protocols are supported by the platform.",
                value =
                    configuredProtocols
                        .joinToString(", "),
                valid = true
            )

        } else {

            checksFailed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.UNSUPPORTED_PROTOCOL,
                severity =
                    SecureSSLSocketFindingSeverity.HIGH,
                title =
                    "Unsupported TLS protocol configured",
                description =
                    "One or more configured TLS protocols are unavailable on the device.",
                value =
                    unsupportedProtocols
                        .joinToString(", "),
                valid = false
            )
        }

        /**
         * ---------------------------------------------------------
         * Cipher-suite configuration
         * ---------------------------------------------------------
         */
        if (
            configuration
                .enabledCipherSuites
                .isNotEmpty()
        ) {

            checksPerformed++

            val unsupportedCiphers =
                configuration
                    .enabledCipherSuites
                    .filterNot {
                        supportedCipherSuitesInternal
                            .contains(it)
                    }

            if (
                unsupportedCiphers.isEmpty()
            ) {

                checksPassed++

                findings += SecureSSLSocketFinding(
                    type =
                        SecureSSLSocketFindingType.CIPHER_CONFIGURATION_VALID,
                    severity =
                        SecureSSLSocketFindingSeverity.INFO,
                    title =
                        "Cipher-suite configuration valid",
                    description =
                        "All explicitly configured cipher suites are supported.",
                    valid = true
                )

            } else {

                checksFailed++

                findings += SecureSSLSocketFinding(
                    type =
                        SecureSSLSocketFindingType.UNSUPPORTED_CIPHER,
                    severity =
                        SecureSSLSocketFindingSeverity.HIGH,
                    title =
                        "Unsupported cipher suite configured",
                    description =
                        "One or more configured cipher suites are unavailable.",
                    value =
                        unsupportedCiphers
                            .joinToString(", "),
                    valid = false
                )
            }
        }

        /**
         * ---------------------------------------------------------
         * Android version
         * ---------------------------------------------------------
         */
        checksPerformed++

        if (
            Build.VERSION.SDK_INT >=
            Build.VERSION_CODES.N
        ) {

            checksPassed++

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.MODERN_ANDROID,
                severity =
                    SecureSSLSocketFindingSeverity.INFO,
                title =
                    "Modern Android TLS platform",
                description =
                    "The application is running on Android API 24 or later.",
                value =
                    Build.VERSION.SDK_INT.toString(),
                valid = true
            )

        } else {

            findings += SecureSSLSocketFinding(
                type =
                    SecureSSLSocketFindingType.LEGACY_ANDROID,
                severity =
                    SecureSSLSocketFindingSeverity.MEDIUM,
                title =
                    "Legacy Android TLS platform",
                description =
                    "The application is running on an older Android API level.",
                value =
                    Build.VERSION.SDK_INT.toString(),
                valid = false
            )
        }

        val valid =
            checksFailed == 0

        return SecureSSLSocketFactoryValidationResult(
            valid = valid,
            findings = findings,
            checksPerformed = checksPerformed,
            checksPassed = checksPassed,
            checksFailed = checksFailed,
            message =
                if (valid) {
                    "SecureSSLSocketFactory validation succeeded."
                } else {
                    "SecureSSLSocketFactory validation completed with security findings."
                }
        )
    }

    companion object {

        /**
         * TLS 1.3.
         */
        const val TLS_1_3 =
            "TLSv1.3"

        /**
         * TLS 1.2.
         */
        const val TLS_1_2 =
            "TLSv1.2"

        /**
         * Recommended default protocol set.
         *
         * TLS 1.2 is retained for compatibility with supported
         * Android/server combinations.
         */
        val DEFAULT_TLS_PROTOCOLS =
            listOf(
                TLS_1_3,
                TLS_1_2
            )

        /**
         * Creates a factory using the default SentriX TLS policy.
         */
        fun create(
            context: Context,
            trustManagerFactoryProvider:
                TrustManagerFactoryProvider
        ): SecureSSLSocketFactory {

            return SecureSSLSocketFactory(
                context =
                    context.applicationContext,
                trustManagerFactoryProvider =
                    trustManagerFactoryProvider,
                configuration =
                    SecureSSLSocketFactoryConfiguration()
            )
        }
    }
}

/**
 * Secure SSL socket factory configuration.
 */
data class SecureSSLSocketFactoryConfiguration(

    /**
     * SSLContext protocol.
     *
     * "TLS" allows the platform to negotiate an appropriate
     * TLS version while the socket itself is restricted to the
     * configured enabledProtocols.
     */
    val sslProtocol: String =
        "TLS",

    /**
     * TLS protocols allowed by SentriX.
     *
     * TLS 1.2 is retained for broad compatibility.
     */
    val enabledProtocols:
        List<String> =
        SecureSSLSocketFactory
            .DEFAULT_TLS_PROTOCOLS,

    /**
     * Explicit cipher-suite allowlist.
     *
     * Empty means use the platform's default secure cipher suites.
     */
    val enabledCipherSuites:
        List<String> =
        emptyList()
)

/**
 * SSL socket factory validation result.
 */
data class SecureSSLSocketFactoryValidationResult(

    /**
     * Whether validation succeeded without failures.
     */
    val valid: Boolean,

    /**
     * Security findings.
     */
    val findings:
        List<SecureSSLSocketFinding>,

    /**
     * Number of checks performed.
     */
    val checksPerformed: Int,

    /**
     * Number of checks passed.
     */
    val checksPassed: Int,

    /**
     * Number of checks failed.
     */
    val checksFailed: Int,

    /**
     * Human-readable summary.
     */
    val message: String
) {

    /**
     * Returns critical findings.
     */
    val criticalFindings:
        List<SecureSSLSocketFinding>
        get() =
            findings.filter {
                it.severity ==
                        SecureSSLSocketFindingSeverity.CRITICAL
            }
}

/**
 * Individual SSL socket security finding.
 */
data class SecureSSLSocketFinding(

    /**
     * Finding type.
     */
    val type:
        SecureSSLSocketFindingType,

    /**
     * Severity.
     */
    val severity:
        SecureSSLSocketFindingSeverity,

    /**
     * Finding title.
     */
    val title: String,

    /**
     * Detailed description.
     */
    val description: String,

    /**
     * Observed value.
     */
    val value: String? = null,

    /**
     * Expected value.
     */
    val expectedValue: String? = null,

    /**
     * Whether the finding passed validation.
     */
    val valid: Boolean
)

/**
 * SSL socket security finding categories.
 */
enum class SecureSSLSocketFindingType {

    /**
     * SSLContext successfully created.
     */
    SSL_CONTEXT_AVAILABLE,

    /**
     * SSLContext unavailable.
     */
    SSL_CONTEXT_UNAVAILABLE,

    /**
     * Platform trust manager available.
     */
    TRUST_MANAGER_AVAILABLE,

    /**
     * Platform trust manager unavailable.
     */
    TRUST_MANAGER_UNAVAILABLE,

    /**
     * TLS 1.3 supported.
     */
    TLS_1_3_SUPPORTED,

    /**
     * TLS 1.3 unavailable.
     */
    TLS_1_3_UNAVAILABLE,

    /**
     * TLS 1.2 supported.
     */
    TLS_1_2_SUPPORTED,

    /**
     * TLS 1.2 unavailable.
     */
    TLS_1_2_UNAVAILABLE,

    /**
     * Configured protocols valid.
     */
    PROTOCOL_CONFIGURATION_VALID,

    /**
     * Unsupported protocol configured.
     */
    UNSUPPORTED_PROTOCOL,

    /**
     * Configured ciphers valid.
     */
    CIPHER_CONFIGURATION_VALID,

    /**
     * Unsupported cipher configured.
     */
    UNSUPPORTED_CIPHER,

    /**
     * Modern Android environment.
     */
    MODERN_ANDROID,

    /**
     * Legacy Android environment.
     */
    LEGACY_ANDROID
}

/**
 * Severity of an SSL socket security finding.
 */
enum class SecureSSLSocketFindingSeverity {

    /**
     * Informational.
     */
    INFO,

    /**
     * Low severity.
     */
    LOW,

    /**
     * Medium severity.
     */
    MEDIUM,

    /**
     * High severity.
     */
    HIGH,

    /**
     * Critical severity.
     */
    CRITICAL
}

/**
 * Exception thrown when a secure SSL socket cannot be created
 * according to the SentriX TLS policy.
 */
class SecureSSLSocketFactoryException(
    message: String
) : IllegalStateException(
    message
)
